### ISSUE TITLE
AOL and Yahoo email

### ISSUE THREAD

**Issue by cjb900** [BuyBitcoinWorldwide/dongleauth#1]
Hi, 

I actually work for AOL and Yahoo and we do now support Yubikeys and Authenticator apps. Information on this can be found in our respective help articles below.
 
**AOL**
Yubikey https://help.aol.com/articles/2-step-verification-with-a-security-key
Authenticator apps https://help.aol.com/articles/2-step-verification-stronger-than-your-password-alone

**Yahoo**
Yubikey https://help.yahoo.com/kb/-step-verification-security-key-sln35380.html
Authenticator https://help.yahoo.com/kb/add-two-step-verification-extra-security-sln5013.html

**Comment by JTuwiner** [comment]
Great, thanks for this update! We will update the page soon

**Comment by JTuwiner** [comment]
This is updated now. Thanks for the heads up
